
/* 

----------           How have I used chatGPT as a "teacher" to make my Accordion open and close dynamically?          ----------------

I started by creating a function that opens and closes my accordion by adding and removing the "ACTIVE" class to my "q-and-a" class,
like this in my "AccordionContent.jsx" file:

    const [active, setActive] = useState(false);

    const handleClick = () => {
        setActive(!active)        
        }

    return (
        <div className='faq-container'>
            <div className={`q-and-a ${active ? 'active': ''}`} onClick={() => handleClick()}>
                <div className="question"><h5 className='question-h5'>{ faqs.title }</h5> <div className='arrow-icon'></div></div>
                <div className="answer"><p className='answer-txt'>{ faqs.description }</p></div>
            </div>
        </div>
    )

I learned this through a tutorial on Youtube that went through how I could do this.

But then I felt that I wanted my accordion to be more dynamic and knew that I had to build the function so that the class "Active"
is removed from the previous element and then added to the "clicked" element with "onClick".
In the video "Enkel formulärhantering i React" I remembered that the teacher mentioned that "Id" can be used as a "KEY" 
when we want to retrieve and change the value of something using "props". 
I did this with the callback function "handleClick". ChatGPT helped me by explaining that this "check" must be done on the "parent" element and not on the "child" element,
to work as I intended. 

This code string is generated by chatGPT: setActive(prev => (prev === id ? false : id))
*/

import React, { useEffect, useState } from 'react'
import './Accordion.css'
import AccordionContent from './AccordionContent'

const Accordion = () => {
    const apiUrl ='https://win25-jsf-assignment.azurewebsites.net/api/faqs'
    const [faqs,setFaqs] = useState([])
    const [active, setActive] = useState(false);
    
    const handleClick = (id) => {
        setActive(prev => (prev === id ? false : id)) /* <------- By chatGPT */
    }
   

    useEffect(() => {
        const getData = async () => {
            try{
                const res = await fetch(apiUrl)
                if(!res.ok){
                    throw new Error(`Status ${res.status}`)
                }
                const data = await res.json()
                setFaqs(data)
                console.log(data)
            }catch(error) {
                console.error(`ERROR $(error)`)
            }
        }
        getData()
    }, [])

  return (
    <>
        {
            faqs.length > 0 && faqs.map(faqs => ( 
            <AccordionContent key={faqs.id}  faqs={faqs} handleClick={handleClick} active={active}/>
            ))
        }
    </>
  )
}

export default Accordion